---
- hosts: kvm
  sudo: yes
  tasks:
    - name: INSTLL APACHE - PHP - MYSQL
      apt: name={{item}} update_cache=yes
      with_items:
        - apache2
        - php5
        - php5-cgi
        - libapache2-mod-php5
        - php5-common
        - php-pear
        - php5-gmp
        - php5-ldap
        - php5-cli
        - mysql-server
    - name: DOWNLOAD PHPIPAM
      get_url:
        url=http://heanet.dl.sourceforge.net/project/phpipam/phpipam-1.2.1.tar
        dest=/tmp
        validate_certs=no
    - name: EXTRACT PHPIPAM
      unarchive:
        src=/tmp/phpipam-1.2.1.tar
        dest=/var/www/html
        copy=no
    - name: COPY FILE CONFIG
      command: cp /var/www/html/phpipam/config.dist.php /var/www/html/phpipam/config.php
    - name: CONFIG FILE config.php
      lineinfile:
        dest=/var/www/html/phpipam/config.php
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
      with_items:
        - {'regexp': $db['user'] = \"phpipam";", 'line': ""}
        - {'regexp': "", 'line': ""}
        - {'regexp': "", 'line': ""}
        - {'regexp': "", 'line': ""}
